'''
Helps validate requests and responses to and from the database.
'''
from pydantic import BaseModel, EmailStr, Field
from typing import Optional
from datetime import datetime, timezone

'''
BaseModels are used to validate the request body of some requests.
Some fields are optional because they are not required for the request, and are instead generated by DB
'''

class CodeBase(BaseModel):
    code_id: Optional[int] # PK
    journal_id: Optional[int]  = None
    code_text = str
    Language = str
    created_at = Optional[datetime] = Field(default_factory=lambda: datetime.now(timezone.utc)) 
    updated_at = Optional[datetime] = Field(default_factory=lambda: datetime.now(timezone.utc))


    class Config:
        orm_mode = True

'''
These classes are used to create new items via API request.
They involve fields involved from request
'''

class CodeCreate(BaseModel):
    code_id: int
    journal_id: int
    code_text: str
    Language: str


'''
These classes represent the actual data of the items.
Empty for now because they inherit all necessary info from the BaseModels
'''

class Code(CodeBase):
    pass