name: Lint and Format for Backend

on:
  push:
    branches:
      - "backend/*" # Match branches starting with "backend/"
      - "dev/backend"
    paths:
      - "backend/**" # Trigger only for changes in backend folder
  pull_request:
    paths:
      - "backend/**" # Trigger only for PRs modifying backend folder

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8

      - name: Run Black
        run: black --check backend/

      - name: Run Flake8
        run: flake8 backend/
