name: Documentation Generation

on:
  push:
    branches:
      - "frontend/**"
      - "dev/frontend"
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies from the frontend directory
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Generate JSDoc
      - name: Generate JSDoc
        working-directory: frontend
        run: npm run docs

    #   # Commit and push documentation
    #   - name: Commit and Push Docs
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.MY_PAT }}
    #     run: |
    #       git config --global user.name "github-actions[bot]"
    #       git config --global user.email "github-actions[bot]@users.noreply.github.com"
    #       git add .
    #       git commit -m "Update JSDoc documentation"
    #       git push https://x-access-token:${GITHUB_TOKEN}@github.com/CSE210Team-06/cse210-fa24-group06.git
