name: Lint and Code Style Check Frontend

on:
  push:
    branches:
      - "main"
      - "frontend/**"
      - "dev/frontend"
    # paths:
    #   - "frontend/**"
  pull_request:
    branches:
      - "main"
      - "frontend/**"
      - "dev/frontend"
    # paths:
    #   - "frontend/**"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # Install dependencies from the frontend directory
      - name: Install dependencies
        working-directory: frontend
        run: npm install

      # Run ESLint
      - name: Run ESLint
        working-directory: frontend
        run: npm run lint

      # Run Prettier for formatting check
      - name: Check code format with Prettier
        working-directory: frontend
        run: npm run prettier
